theme = "nord"
icons = "awesome"

[[block]]
block = "net"
#format = "{ssid} {signal_strength} {ip} {speed_down;K*b} {graph_down;K*b}"
format = "{speed_down;K*b} {speed_up;K*b}"
interval = 5

[[block]]
block = "disk_space"
path = "/home"
alias = "/"
info_type = "used"
format = "{icon} {percentage}"
unit = "GB"
interval = 20
warning = 60.0
alert = 80.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used_percents}"
format_swap = "{swap_used_percents}"

[[block]]
block = "cpu"
interval = 3
format = "{utilization} {frequency}"

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 5
format = "%Y-%m-%d %H:%M:%S"
