[theme]
theme = "nord"

[icons]
icons = "awesome4"

[[block]]
block = "notify"
format = " $icon {($notification_count.eng(w:1)) |} "

[[block.click]]
button = "left"
action = "show"

[[block.click]]
button = "right"
action = "toggle_paused"

[[block]]
block = "net"
#format = "{ssid} {signal_strength} {ip} {speed_down;K*b} {graph_down;K*b}"
#format = "{speed_down;K*b} {speed_up;K*b}"

format = " $icon ^icon_net_down $speed_down.eng(prefix:K) ^icon_net_up $speed_up.eng(prefix:K)"
#interval = 5

[[block]]
block = "disk_space"
path = "/home"
info_type = "used"
format = " $icon $percentage"
interval = 20
alert = 90
warning = 80

[[block]]
block = "memory"
#display_type = "memory"
format = " $icon$mem_used_percents"

[[block]]
block = "cpu"
interval = 3
format = " $icon$utilization $frequency"

[[block]]
block = "temperature"
#collapsed = false
interval = 10
format = " $icon $average"
chip = "k10temp-pci-00c3"
inputs = ["Tctl"]

#[[block]]
#block = "nvidia_gpu"
#interval = 5

[[block]]
block = "load"
interval = 1

[[block]]
block = "sound"
driver = "pulseaudio"
device_kind = "source"

[[block]]
block = "sound"
driver = "pulseaudio"

[[block]]
block = "time"
interval = 5
format = " $icon $timestamp.datetime(f:'%Y-%m-%d %H:%M:%S')"
