version: "3.9"

services:
  postgres:
    image: postgres:13.1
    environment:
    - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
    - postgres:/var/lib/postgresql/data
  backend:
    image: python:3.9
    volumes:
    - ./backend:/app
    depends_on:
    - postgres

volumes:
  postgres: {}
